// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    role: { id: string; displayField: string };
    email: string;
  };

  type MencariTableRow = {
    id: string;
    name: string;
    bloodType: string;
    rhesus: string;
    provinsi: string;
    kota: string;
    phone: string;
    socialMedia: string;
  };

  type MenjadiTableRow = {
    id: string;
    name: string;
    bloodType: string;
    rhesus: string;
    provinsi: string;
    kota: string;
    phone: string;
    socialMedia: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
    };
    write: {
      email: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllMencariViewRow = {
    read: {
      id: string;
      name: string;
      bloodType: string;
      rhesus: string;
      provinsi: string;
      kota: string;
      phone: string;
      socialMedia: string;
    };
    write: {
      name: string;
      bloodType: string;
      rhesus: string;
      provinsi: string;
      kota: string;
      phone: string;
      socialMedia: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllMenjadiViewRow = {
    read: {
      id: string;
      name: string;
      bloodType: string;
      rhesus: string;
      provinsi: string;
      kota: string;
      phone: string;
      socialMedia: string;
    };
    write: {
      name: string;
      bloodType: string;
      rhesus: string;
      provinsi: string;
      kota: string;
      phone: string;
      socialMedia: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    allMencari: AllMencariViewRow;
    allMenjadi: AllMenjadiViewRow;
  };
}
